development:
    adapter: postgresql
    database: elevate
    host: localhost
    username: kevinwu
    pool: 5
    timeout: 5000

test:
    adapter: postgresql
    database: elevateTest
    host: localhost
    username: kevinwu
    pool: 5
    timeout: 5000
